name: Convert YAML to Swagger JSON
on:
  push:
    paths:
      - 'test-api.yaml'

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pull-requests: write  # To create a PR from that branch
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Choose the desired Node.js version

      - name: Install swagger-cli
        run: npm install -g swagger-cli

      - name: Convert YAML to JSON
        run: |
          # Replace 'path/to/your/swagger.yaml' and 'path/to/output/swagger.json' with your file paths
          swagger-cli bundle test-api.yaml --type=json --outfile=test-swagger.json
      # Commit the updated Swagger JSON file back to the repository
      - name: Commit JSON File
        run: |
          git config --global user.name 'Karthika-Manoharan'
          git config --global user.email 'karthika.manoharan@freshworks.com'
          git add test-swagger.json
          git commit -m "Auto-generated Swagger JSON For Test Api"
          git push
